variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode"
  POSTGRES_IMAGE: "postgres:14.4-alpine3.16"

cache:
  paths:
    - .m2/repository

stages:
  - build

build-server:
  stage: build
  image: maven:3.8.3-openjdk-17
  services:
    - name: $POSTGRES_IMAGE
      alias: postgres
  variables:
    POSTGRES_HOST: 'postgres'
    POSTGRES_DB: 'onboarding'
    POSTGRES_USER: 'onboarding'
    POSTGRES_PASSWORD: 'onboarding'
    DB_URL: "jdbc:postgresql://postgres:5432/onboarding"
  script:
    - mvn -f ./pom.xml $MAVEN_CLI_OPTS verify
