ALTER TABLE floors
    ADD COLUMN IF NOT EXISTS image_id BIGINT,
    ADD CONSTRAINT FK_FLOORS_ON_IMAGE FOREIGN KEY (image_id) REFERENCES images (id),
    DROP COLUMN map_floor;

ALTER TABLE employees
    ADD COLUMN IF NOT EXISTS image_id BIGINT,
    ADD CONSTRAINT FK_EMPLOYEES_ON_IMAGE FOREIGN KEY (image_id) REFERENCES images (id),
    DROP COLUMN photo;
