CREATE TABLE IF NOT EXISTS fav_place
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id  BIGINT,
    workplace_id BIGINT,
    CONSTRAINT pk_fav_place PRIMARY KEY (id),
    CONSTRAINT FK_FAV_PLACE_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id),
    CONSTRAINT FK_FAV_PLACE_ON_WORKPLACE FOREIGN KEY (workplace_id) REFERENCES workplaces (id)
);

CREATE INDEX IF NOT EXISTS employee_place_fav_place ON fav_place (employee_id, workplace_id);
CREATE INDEX IF NOT EXISTS employee_fav_place ON fav_place (employee_id);
CREATE INDEX IF NOT EXISTS workplace_fav_place ON fav_place (workplace_id);
