CREATE TABLE IF NOT EXISTS bookings
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_time_of_start TIMESTAMP WITHOUT TIME ZONE,
    date_time_of_end   TIMESTAMP WITHOUT TIME ZONE,
    guests             INTEGER                                 NOT NULL,
    CONSTRAINT pk_bookings PRIMARY KEY (id)
);
