CREATE TABLE IF NOT EXISTS floors
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    floor_number INTEGER,
    map_floor    VARCHAR(255),
    CONSTRAINT pk_floors PRIMARY KEY (id)
);
