CREATE TABLE IF NOT EXISTS conference_members
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id BIGINT,
    booking_id  BIGINT,
    CONSTRAINT pk_conference_members PRIMARY KEY (id),
    CONSTRAINT FK_CONFERENCE_MEMBERS_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id)
);
